"""
Python 3 Interface of erl_gaussian_process
"""
from __future__ import annotations
import collections.abc
import erl_covariance.pyerl_covariance
import erl_geometry.pyerl_geometry
import numpy
import numpy.typing
import typing
__all__: list[str] = ['LidarGaussianProcess2Dd', 'LidarGaussianProcess2Df', 'MappingD', 'MappingF', 'MappingType', 'NoisyInputGaussianProcessD', 'NoisyInputGaussianProcessF', 'RangeSensorGaussianProcess3Dd', 'RangeSensorGaussianProcess3Df', 'VanillaGaussianProcessD', 'VanillaGaussianProcessF', 'YamlableBase', 'exp', 'identity', 'inverse', 'inverse_sqrt', 'log', 'sigmoid', 'tanh', 'unknown']
class LidarGaussianProcess2Dd:
    class Setting(YamlableBase):
        gp: VanillaGaussianProcessD.Setting
        mapping: MappingD.Setting
        partition_on_hit_rays: bool
        sensor_frame: erl_geometry.pyerl_geometry.LidarFrame2Dd.Setting
        symmetric_partitions: bool
        def __init__(self) -> None:
            ...
        @property
        def discontinuity_var(self) -> float:
            ...
        @discontinuity_var.setter
        def discontinuity_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def group_size(self) -> int:
            ...
        @group_size.setter
        def group_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def init_variance(self) -> float:
            ...
        @init_variance.setter
        def init_variance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def margin(self) -> int:
            ...
        @margin.setter
        def margin(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def max_valid_range_var(self) -> float:
            ...
        @max_valid_range_var.setter
        def max_valid_range_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def occ_test_temperature(self) -> float:
            ...
        @occ_test_temperature.setter
        def occ_test_temperature(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def overlap_size(self) -> int:
            ...
        @overlap_size.setter
        def overlap_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def sensor_range_var(self) -> float:
            ...
        @sensor_range_var.setter
        def sensor_range_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class TestResult:
        def get_ktest(self, index: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, parallel: bool) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
            ...
        @typing.overload
        def get_mean(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, float]:
            ...
        @typing.overload
        def get_variance(self, parallel: bool) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
            ...
        @typing.overload
        def get_variance(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, float]:
            ...
        @property
        def num_test(self) -> int:
            ...
    def __init__(self, setting: LidarGaussianProcess2Dd.Setting) -> None:
        ...
    def compute_occ(self, pos_local: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]) -> dict:
        ...
    def partition_on_angles(self) -> None:
        ...
    def partition_on_hit_rays(self) -> None:
        ...
    def reset(self) -> None:
        ...
    def search_partition(self, angle_local: typing.SupportsFloat | typing.SupportsIndex) -> int:
        ...
    def store_data(self, rotation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 2]"], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], ranges: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> bool:
        ...
    def test(self, angles: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], angles_are_local: bool, un_map: bool) -> LidarGaussianProcess2Dd.TestResult:
        ...
    def train(self, rotation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 2]"], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], ranges: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> bool:
        ...
    @property
    def angle_partitions(self) -> list[tuple[int, int, float, float]]:
        ...
    @property
    def gps(self) -> list[VanillaGaussianProcessD]:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def sensor_frame(self) -> erl_geometry.pyerl_geometry.LidarFrame2Dd:
        ...
    @property
    def setting(self) -> LidarGaussianProcess2Dd.Setting:
        ...
class LidarGaussianProcess2Df:
    class Setting(YamlableBase):
        gp: VanillaGaussianProcessF.Setting
        mapping: MappingF.Setting
        partition_on_hit_rays: bool
        sensor_frame: erl_geometry.pyerl_geometry.LidarFrame2Df.Setting
        symmetric_partitions: bool
        def __init__(self) -> None:
            ...
        @property
        def discontinuity_var(self) -> float:
            ...
        @discontinuity_var.setter
        def discontinuity_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def group_size(self) -> int:
            ...
        @group_size.setter
        def group_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def init_variance(self) -> float:
            ...
        @init_variance.setter
        def init_variance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def margin(self) -> int:
            ...
        @margin.setter
        def margin(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def max_valid_range_var(self) -> float:
            ...
        @max_valid_range_var.setter
        def max_valid_range_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def occ_test_temperature(self) -> float:
            ...
        @occ_test_temperature.setter
        def occ_test_temperature(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def overlap_size(self) -> int:
            ...
        @overlap_size.setter
        def overlap_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def sensor_range_var(self) -> float:
            ...
        @sensor_range_var.setter
        def sensor_range_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class TestResult:
        def get_ktest(self, index: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, parallel: bool) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]]:
            ...
        @typing.overload
        def get_mean(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, float]:
            ...
        @typing.overload
        def get_variance(self, parallel: bool) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]]:
            ...
        @typing.overload
        def get_variance(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, float]:
            ...
        @property
        def num_test(self) -> int:
            ...
    def __init__(self, setting: LidarGaussianProcess2Df.Setting) -> None:
        ...
    def compute_occ(self, pos_local: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"]) -> dict:
        ...
    def partition_on_angles(self) -> None:
        ...
    def partition_on_hit_rays(self) -> None:
        ...
    def reset(self) -> None:
        ...
    def search_partition(self, angle_local: typing.SupportsFloat | typing.SupportsIndex) -> int:
        ...
    def store_data(self, rotation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 2]"], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"], ranges: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, 1]"]) -> bool:
        ...
    def test(self, angles: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"], angles_are_local: bool, un_map: bool) -> LidarGaussianProcess2Df.TestResult:
        ...
    def train(self, rotation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 2]"], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"], ranges: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, 1]"]) -> bool:
        ...
    @property
    def angle_partitions(self) -> list[tuple[int, int, float, float]]:
        ...
    @property
    def gps(self) -> list[VanillaGaussianProcessF]:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def sensor_frame(self) -> erl_geometry.pyerl_geometry.LidarFrame2Df:
        ...
    @property
    def setting(self) -> LidarGaussianProcess2Df.Setting:
        ...
class MappingD:
    class Setting(YamlableBase):
        type: MappingType
        def __init__(self) -> None:
            ...
        @property
        def scale(self) -> float:
            ...
        @scale.setter
        def scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, setting: MappingD.Setting) -> None:
        ...
    @property
    def inv(self) -> collections.abc.Callable[[typing.SupportsFloat | typing.SupportsIndex], float]:
        ...
    @property
    def map(self) -> collections.abc.Callable[[typing.SupportsFloat | typing.SupportsIndex], float]:
        ...
    @property
    def setting(self) -> MappingD.Setting:
        ...
class MappingF:
    class Setting(YamlableBase):
        type: MappingType
        def __init__(self) -> None:
            ...
        @property
        def scale(self) -> float:
            ...
        @scale.setter
        def scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, setting: MappingF.Setting) -> None:
        ...
    @property
    def inv(self) -> collections.abc.Callable[[typing.SupportsFloat | typing.SupportsIndex], float]:
        ...
    @property
    def map(self) -> collections.abc.Callable[[typing.SupportsFloat | typing.SupportsIndex], float]:
        ...
    @property
    def setting(self) -> MappingF.Setting:
        ...
class MappingType:
    """
    Members:
    
      identity
    
      inverse
    
      inverse_sqrt
    
      exp
    
      log
    
      tanh
    
      sigmoid
    
      unknown
    """
    __members__: typing.ClassVar[dict[str, MappingType]]  # value = {'identity': <MappingType.identity: 0>, 'inverse': <MappingType.inverse: 1>, 'inverse_sqrt': <MappingType.inverse_sqrt: 2>, 'exp': <MappingType.exp: 3>, 'log': <MappingType.log: 4>, 'tanh': <MappingType.tanh: 5>, 'sigmoid': <MappingType.sigmoid: 6>, 'unknown': <MappingType.unknown: 7>}
    exp: typing.ClassVar[MappingType]  # value = <MappingType.exp: 3>
    identity: typing.ClassVar[MappingType]  # value = <MappingType.identity: 0>
    inverse: typing.ClassVar[MappingType]  # value = <MappingType.inverse: 1>
    inverse_sqrt: typing.ClassVar[MappingType]  # value = <MappingType.inverse_sqrt: 2>
    log: typing.ClassVar[MappingType]  # value = <MappingType.log: 4>
    sigmoid: typing.ClassVar[MappingType]  # value = <MappingType.sigmoid: 6>
    tanh: typing.ClassVar[MappingType]  # value = <MappingType.tanh: 5>
    unknown: typing.ClassVar[MappingType]  # value = <MappingType.unknown: 7>
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __ge__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __gt__(self, other: typing.Any) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __le__(self, other: typing.Any) -> bool:
        ...
    def __lt__(self, other: typing.Any) -> bool:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class NoisyInputGaussianProcessD:
    class Setting(YamlableBase):
        kernel: erl_covariance.pyerl_covariance.CovarianceD.Setting
        kernel_setting_type: str
        kernel_type: str
        no_gradient_observation: bool
        def __init__(self) -> None:
            ...
        @property
        def max_num_samples(self) -> int:
            ...
        @max_num_samples.setter
        def max_num_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    class TestResult:
        @typing.overload
        def get_covariance(self, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
            ...
        @typing.overload
        def get_covariance(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @typing.overload
        def get_gradient(self, y_index: typing.SupportsInt | typing.SupportsIndex, parallel: bool) -> dict:
            ...
        @typing.overload
        def get_gradient(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @typing.overload
        def get_gradient_variance(self, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
            ...
        @typing.overload
        def get_gradient_variance(self, index: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, y_index: typing.SupportsInt | typing.SupportsIndex, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> float:
            ...
        @typing.overload
        def get_mean_variance(self, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean_variance(self, index: typing.SupportsInt | typing.SupportsIndex) -> float:
            ...
        @property
        def k_test(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
            ...
        @property
        def num_test(self) -> int:
            ...
    class TrainBuf:
        @property
        def grad(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
            ...
        @grad.setter
        def grad(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
            ...
        @property
        def grad_flag(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int64], "[m, 1]"]:
            ...
        @grad_flag.setter
        def grad_flag(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.int64, "[m, 1]"]) -> None:
            ...
        @property
        def num_samples(self) -> int:
            ...
        @num_samples.setter
        def num_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def num_samples_with_grad(self) -> int:
            ...
        @num_samples_with_grad.setter
        def num_samples_with_grad(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def var_grad(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @var_grad.setter
        def var_grad(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
            ...
        @property
        def var_x(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @var_x.setter
        def var_x(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
            ...
        @property
        def var_y(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @var_y.setter
        def var_y(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
            ...
        @property
        def x(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
            ...
        @x.setter
        def x(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
            ...
        @property
        def x_dim(self) -> int:
            ...
        @x_dim.setter
        def x_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def y(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
            ...
        @y.setter
        def y(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
            ...
        @property
        def y_dim(self) -> int:
            ...
        @y_dim.setter
        def y_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    def __init__(self, setting: NoisyInputGaussianProcessD.Setting) -> None:
        ...
    def reset(self, max_num_samples: typing.SupportsInt | typing.SupportsIndex, x_dim: typing.SupportsInt | typing.SupportsIndex, y_dim: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def test(self, mat_x_test: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], predict_gradient: bool) -> NoisyInputGaussianProcessD.TestResult:
        ...
    def train(self, mat_x_train: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], mat_y_train: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], mat_grad_train: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], vec_grad_flag: typing.Annotated[numpy.typing.NDArray[numpy.int64], "[m, 1]"], vec_var_x: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], vec_var_y: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], vec_var_grad: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> bool:
        ...
    def update_ktrain(self) -> bool:
        ...
    @property
    def alpha(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @property
    def buf_loading(self) -> NoisyInputGaussianProcessD.TrainBuf:
        ...
    @property
    def buf_train(self) -> NoisyInputGaussianProcessD.TrainBuf:
        ...
    @property
    def cholesky_k_train(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def k_train(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @property
    def kernel(self) -> erl_covariance.pyerl_covariance.CovarianceD:
        ...
    @property
    def memory_usage(self) -> int:
        ...
    @property
    def setting(self) -> NoisyInputGaussianProcessD.Setting:
        ...
    @property
    def using_reduced_rank_kernel(self) -> bool:
        ...
class NoisyInputGaussianProcessF:
    class Setting(YamlableBase):
        kernel: erl_covariance.pyerl_covariance.CovarianceF.Setting
        kernel_setting_type: str
        kernel_type: str
        no_gradient_observation: bool
        def __init__(self) -> None:
            ...
        @property
        def max_num_samples(self) -> int:
            ...
        @max_num_samples.setter
        def max_num_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    class TestResult:
        @typing.overload
        def get_covariance(self, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
            ...
        @typing.overload
        def get_covariance(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @typing.overload
        def get_gradient(self, y_index: typing.SupportsInt | typing.SupportsIndex, parallel: bool) -> dict:
            ...
        @typing.overload
        def get_gradient(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @typing.overload
        def get_gradient_variance(self, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
            ...
        @typing.overload
        def get_gradient_variance(self, index: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, y_index: typing.SupportsInt | typing.SupportsIndex, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> float:
            ...
        @typing.overload
        def get_mean_variance(self, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean_variance(self, index: typing.SupportsInt | typing.SupportsIndex) -> float:
            ...
        @property
        def k_test(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
            ...
        @property
        def num_test(self) -> int:
            ...
    class TrainBuf:
        @property
        def grad(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
            ...
        @grad.setter
        def grad(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> None:
            ...
        @property
        def grad_flag(self) -> typing.Annotated[numpy.typing.NDArray[numpy.int64], "[m, 1]"]:
            ...
        @grad_flag.setter
        def grad_flag(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.int64, "[m, 1]"]) -> None:
            ...
        @property
        def num_samples(self) -> int:
            ...
        @num_samples.setter
        def num_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def num_samples_with_grad(self) -> int:
            ...
        @num_samples_with_grad.setter
        def num_samples_with_grad(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def var_grad(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @var_grad.setter
        def var_grad(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, 1]"]) -> None:
            ...
        @property
        def var_x(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @var_x.setter
        def var_x(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, 1]"]) -> None:
            ...
        @property
        def var_y(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @var_y.setter
        def var_y(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, 1]"]) -> None:
            ...
        @property
        def x(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
            ...
        @x.setter
        def x(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> None:
            ...
        @property
        def x_dim(self) -> int:
            ...
        @x_dim.setter
        def x_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def y(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
            ...
        @y.setter
        def y(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> None:
            ...
        @property
        def y_dim(self) -> int:
            ...
        @y_dim.setter
        def y_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    def __init__(self, setting: NoisyInputGaussianProcessF.Setting) -> None:
        ...
    def reset(self, max_num_samples: typing.SupportsInt | typing.SupportsIndex, x_dim: typing.SupportsInt | typing.SupportsIndex, y_dim: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def test(self, mat_x_test: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], predict_gradient: bool) -> NoisyInputGaussianProcessF.TestResult:
        ...
    def train(self, mat_x_train: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], mat_y_train: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], mat_grad_train: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], vec_grad_flag: typing.Annotated[numpy.typing.NDArray[numpy.int64], "[m, 1]"], vec_var_x: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"], vec_var_y: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"], vec_var_grad: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]) -> bool:
        ...
    def update_ktrain(self) -> bool:
        ...
    @property
    def alpha(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
        ...
    @property
    def buf_loading(self) -> NoisyInputGaussianProcessF.TrainBuf:
        ...
    @property
    def buf_train(self) -> NoisyInputGaussianProcessF.TrainBuf:
        ...
    @property
    def cholesky_k_train(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def k_train(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
        ...
    @property
    def kernel(self) -> erl_covariance.pyerl_covariance.CovarianceF:
        ...
    @property
    def memory_usage(self) -> int:
        ...
    @property
    def setting(self) -> NoisyInputGaussianProcessF.Setting:
        ...
    @property
    def using_reduced_rank_kernel(self) -> bool:
        ...
class RangeSensorGaussianProcess3Dd:
    class Setting(YamlableBase):
        gp: VanillaGaussianProcessD.Setting
        mapping: MappingD.Setting
        sensor_frame: erl_geometry.pyerl_geometry.RangeSensorFrame3Dd.Setting
        sensor_frame_setting_type: str
        sensor_frame_type: str
        def __init__(self) -> None:
            ...
        @property
        def col_group_size(self) -> int:
            ...
        @col_group_size.setter
        def col_group_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def col_margin(self) -> int:
            ...
        @col_margin.setter
        def col_margin(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def col_overlap_size(self) -> int:
            ...
        @col_overlap_size.setter
        def col_overlap_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def init_variance(self) -> float:
            ...
        @init_variance.setter
        def init_variance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_valid_range_var(self) -> float:
            ...
        @max_valid_range_var.setter
        def max_valid_range_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_num_samples_per_group(self) -> int:
            ...
        @min_num_samples_per_group.setter
        def min_num_samples_per_group(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def occ_test_temperature(self) -> float:
            ...
        @occ_test_temperature.setter
        def occ_test_temperature(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def row_group_size(self) -> int:
            ...
        @row_group_size.setter
        def row_group_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def row_margin(self) -> int:
            ...
        @row_margin.setter
        def row_margin(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def row_overlap_size(self) -> int:
            ...
        @row_overlap_size.setter
        def row_overlap_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def sensor_range_var(self) -> float:
            ...
        @sensor_range_var.setter
        def sensor_range_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class TestResult:
        def get_ktest(self, index: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, parallel: bool) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
            ...
        @typing.overload
        def get_mean(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, float]:
            ...
        @typing.overload
        def get_variance(self, parallel: bool) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]:
            ...
        @typing.overload
        def get_variance(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, float]:
            ...
        @property
        def num_test(self) -> int:
            ...
    def __init__(self, setting: RangeSensorGaussianProcess3Dd.Setting) -> None:
        ...
    def compute_occ(self, pos_local: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> dict:
        ...
    def reset(self) -> None:
        ...
    def search_partition(self, frame_coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]) -> tuple[int, int]:
        ...
    def store_data(self, rotation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], ranges: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> bool:
        ...
    def test(self, directions: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, n]", "flags.f_contiguous"], directions_are_local: bool, un_map: bool) -> RangeSensorGaussianProcess3Dd.TestResult:
        ...
    def train(self, rotation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 3]"], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], ranges: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> bool:
        ...
    @property
    def col_partitions(self) -> list[tuple[int, int, float, float]]:
        ...
    @property
    def gps(self) -> list:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def mapping(self) -> MappingD:
        ...
    @property
    def row_partitions(self) -> list[tuple[int, int, float, float]]:
        ...
    @property
    def sensor_frame(self) -> erl_geometry.pyerl_geometry.RangeSensorFrame3Dd:
        ...
    @property
    def setting(self) -> RangeSensorGaussianProcess3Dd.Setting:
        ...
class RangeSensorGaussianProcess3Df:
    class Setting(YamlableBase):
        gp: VanillaGaussianProcessF.Setting
        mapping: MappingF.Setting
        sensor_frame: erl_geometry.pyerl_geometry.RangeSensorFrame3Df.Setting
        sensor_frame_setting_type: str
        sensor_frame_type: str
        def __init__(self) -> None:
            ...
        @property
        def col_group_size(self) -> int:
            ...
        @col_group_size.setter
        def col_group_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def col_margin(self) -> int:
            ...
        @col_margin.setter
        def col_margin(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def col_overlap_size(self) -> int:
            ...
        @col_overlap_size.setter
        def col_overlap_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def init_variance(self) -> float:
            ...
        @init_variance.setter
        def init_variance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_valid_range_var(self) -> float:
            ...
        @max_valid_range_var.setter
        def max_valid_range_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_num_samples_per_group(self) -> int:
            ...
        @min_num_samples_per_group.setter
        def min_num_samples_per_group(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def occ_test_temperature(self) -> float:
            ...
        @occ_test_temperature.setter
        def occ_test_temperature(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def row_group_size(self) -> int:
            ...
        @row_group_size.setter
        def row_group_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def row_margin(self) -> int:
            ...
        @row_margin.setter
        def row_margin(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def row_overlap_size(self) -> int:
            ...
        @row_overlap_size.setter
        def row_overlap_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def sensor_range_var(self) -> float:
            ...
        @sensor_range_var.setter
        def sensor_range_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class TestResult:
        def get_ktest(self, index: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, parallel: bool) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]]:
            ...
        @typing.overload
        def get_mean(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, float]:
            ...
        @typing.overload
        def get_variance(self, parallel: bool) -> tuple[typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"], typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]]:
            ...
        @typing.overload
        def get_variance(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, float]:
            ...
        @property
        def num_test(self) -> int:
            ...
    def __init__(self, setting: RangeSensorGaussianProcess3Df.Setting) -> None:
        ...
    def compute_occ(self, pos_local: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]) -> dict:
        ...
    def reset(self) -> None:
        ...
    def search_partition(self, frame_coords: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"]) -> tuple[int, int]:
        ...
    def store_data(self, rotation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 3]"], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"], ranges: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> bool:
        ...
    def test(self, directions: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, n]", "flags.f_contiguous"], directions_are_local: bool, un_map: bool) -> RangeSensorGaussianProcess3Df.TestResult:
        ...
    def train(self, rotation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 3]"], translation: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"], ranges: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> bool:
        ...
    @property
    def col_partitions(self) -> list[tuple[int, int, float, float]]:
        ...
    @property
    def gps(self) -> list:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def mapping(self) -> MappingF:
        ...
    @property
    def row_partitions(self) -> list[tuple[int, int, float, float]]:
        ...
    @property
    def sensor_frame(self) -> erl_geometry.pyerl_geometry.RangeSensorFrame3Df:
        ...
    @property
    def setting(self) -> RangeSensorGaussianProcess3Df.Setting:
        ...
class VanillaGaussianProcessD:
    class Setting(YamlableBase):
        kernel: erl_covariance.pyerl_covariance.CovarianceD.Setting
        kernel_setting_type: str
        kernel_type: str
        def __init__(self) -> None:
            ...
        @property
        def max_num_samples(self) -> int:
            ...
        @max_num_samples.setter
        def max_num_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    class TestResult:
        @typing.overload
        def get_mean(self, y_index: typing.SupportsInt | typing.SupportsIndex, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> float:
            ...
        @typing.overload
        def get_variance(self, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @typing.overload
        def get_variance(self, index: typing.SupportsInt | typing.SupportsIndex) -> float:
            ...
        @property
        def k_test(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
            ...
        @property
        def num_test(self) -> int:
            ...
    class TrainBuf:
        @property
        def num_samples(self) -> int:
            ...
        @num_samples.setter
        def num_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def var(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]:
            ...
        @var.setter
        def var(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, 1]"]) -> None:
            ...
        @property
        def x(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
            ...
        @x.setter
        def x(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
            ...
        @property
        def x_dim(self) -> int:
            ...
        @x_dim.setter
        def x_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def y(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
            ...
        @y.setter
        def y(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> None:
            ...
        @property
        def y_dim(self) -> int:
            ...
        @y_dim.setter
        def y_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    def __init__(self, setting: VanillaGaussianProcessD.Setting) -> None:
        ...
    def reset(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def test(self, mat_x_test: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"]) -> VanillaGaussianProcessD.TestResult:
        ...
    def train(self, mat_x_train: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], mat_y_train: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], vec_var_y: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]) -> bool:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def setting(self) -> VanillaGaussianProcessD.Setting:
        ...
class VanillaGaussianProcessF:
    class Setting(YamlableBase):
        kernel: erl_covariance.pyerl_covariance.CovarianceF.Setting
        kernel_setting_type: str
        kernel_type: str
        def __init__(self) -> None:
            ...
        @property
        def max_num_samples(self) -> int:
            ...
        @max_num_samples.setter
        def max_num_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    class TestResult:
        @typing.overload
        def get_mean(self, y_index: typing.SupportsInt | typing.SupportsIndex, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @typing.overload
        def get_mean(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> float:
            ...
        @typing.overload
        def get_variance(self, parallel: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @typing.overload
        def get_variance(self, index: typing.SupportsInt | typing.SupportsIndex) -> float:
            ...
        @property
        def k_test(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
            ...
        @property
        def num_test(self) -> int:
            ...
    class TrainBuf:
        @property
        def num_samples(self) -> int:
            ...
        @num_samples.setter
        def num_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def var(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]:
            ...
        @var.setter
        def var(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, 1]"]) -> None:
            ...
        @property
        def x(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
            ...
        @x.setter
        def x(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> None:
            ...
        @property
        def x_dim(self) -> int:
            ...
        @x_dim.setter
        def x_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def y(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
            ...
        @y.setter
        def y(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> None:
            ...
        @property
        def y_dim(self) -> int:
            ...
        @y_dim.setter
        def y_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    def __init__(self, setting: VanillaGaussianProcessF.Setting) -> None:
        ...
    def reset(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def test(self, mat_x_test: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"]) -> VanillaGaussianProcessF.TestResult:
        ...
    def train(self, mat_x_train: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], mat_y_train: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], vec_var_y: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"]) -> bool:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def setting(self) -> VanillaGaussianProcessF.Setting:
        ...
class YamlableBase:
    def __str__(self) -> str:
        ...
    def as_yaml_file(self, yaml_file: str) -> None:
        ...
    def as_yaml_string(self) -> str:
        ...
    def from_command_line(self, args: collections.abc.Sequence[str]) -> bool:
        ...
    def from_yaml_file(self, yaml_file: str, base_config_field: str) -> bool:
        ...
    def from_yaml_string(self, yaml_str: str) -> bool:
        ...
exp: MappingType  # value = <MappingType.exp: 3>
identity: MappingType  # value = <MappingType.identity: 0>
inverse: MappingType  # value = <MappingType.inverse: 1>
inverse_sqrt: MappingType  # value = <MappingType.inverse_sqrt: 2>
log: MappingType  # value = <MappingType.log: 4>
sigmoid: MappingType  # value = <MappingType.sigmoid: 6>
tanh: MappingType  # value = <MappingType.tanh: 5>
unknown: MappingType  # value = <MappingType.unknown: 7>
